# Build with:
# 	docker build -t benchservice .
# Run with
# 	docker run --name gobenchservice -e "benchredis=192.168.50.235:6374" -t benchservice
#   docker start/stop gobenchservice
FROM golang:1.10-alpine3.7
RUN echo "version1" && apk add --no-cache git mercurial g++ \
	&& go get -v github.com/schollz/git \
	&& go install -v github.com/schollz/git
ENV PATH "$GOPATH/bin:$PATH"
RUN go get -v github.com/schollz/gobenchmarkservice ; \
go install -v github.com/schollz/gobenchmarkservice ; \
go get -v github.com/gorilla/mux ; \ 
go get -v github.com/go-sql-driver/mysql ; \ 
go get -v github.com/codegangsta/cli ; \ 
go get -v github.com/lib/pq ; \ 
go get -v github.com/mattn/go-sqlite3 ; \ 
go get -v github.com/gorilla/websocket ; \ 
go get -v github.com/garyburd/redigo/redis ; \ 
go get -v github.com/gin-gonic/gin ; \ 
go get -v github.com/PuerkitoBio/goquery ; \ 
go get -v github.com/go-martini/martini ; \ 
go get -v github.com/golang/protobuf/proto ; \ 
go get -v github.com/julienschmidt/httprouter ; \ 
go get -v github.com/BurntSushi/toml ; \ 
go get -v github.com/boltdb/bolt ; \ 
go get -v github.com/gorilla/sessions ; \ 
go get -v github.com/satori/go.uuid ; \ 
go get -v github.com/spf13/cobra ; \ 
go get -v github.com/jinzhu/gorm ; \ 
go get -v github.com/russross/blackfriday ; \ 
go get -v github.com/codegangsta/negroni ; \ 
go get -v github.com/spf13/viper ; \ 
go get -v github.com/fatih/color ; \ 
go get -v github.com/astaxie/beego ; \ 
go get -v github.com/gorilla/context ; \ 
go get -v github.com/dgrijalva/jwt-go ; \ 
go get -v github.com/jmoiron/sqlx ; \ 
go get -v github.com/google/go-github/github ; \ 
go get -v github.com/nu7hatch/gouuid ; \ 
go get -v github.com/martini-contrib/render ; \ 
go get -v github.com/nsf/termbox-go ; \ 
go get -v github.com/codegangsta/martini ; \ 
go get -v github.com/pkg/errors ; \ 
go get -v github.com/nfnt/resize ; \ 
go get -v github.com/dustin/go-humanize ; \ 
go get -v github.com/jessevdk/go-flags ; \ 
go get -v github.com/streadway/amqp ; \ 
go get -v github.com/pborman/uuid ; \ 
go get -v github.com/gorilla/securecookie ; \ 
go get -v github.com/zenazn/goji/web ; \ 
go get -v github.com/davecgh/go-spew/spew ; \ 
go get -v github.com/howeyc/fsnotify ; \ 
go get -v github.com/labstack/echo ; \ 
go get -v github.com/gorilla/handlers ; \ 
go get -v github.com/revel/revel ; \ 
go get -v github.com/bitly/go-simplejson ; \ 
go get -v github.com/urfave/cli ; \ 
go get -v github.com/syndtr/goleveldb/leveldb ; \ 
go get -v github.com/prometheus/client_golang/prometheus ; \ 
go get -v github.com/kardianos/osext ; \ 
go get -v github.com/hashicorp/consul/api ; \ 
go get -v github.com/mitchellh/mapstructure ; \ 
go get -v github.com/unrolled/render ; \ 
go get -v github.com/coopernurse/gorp ; \ 
go get -v github.com/mitchellh/go-homedir ; \ 
go get -v github.com/mgutz/ansi ; \ 
go get -v github.com/ChimeraCoder/anaconda ; \ 
go get -v github.com/rcrowley/go-metrics ; \ 
go get -v github.com/gogo/protobuf/proto ; \ 
go get -v github.com/rs/cors ; \ 
go get -v github.com/docopt/docopt-go ; \ 
go get -v github.com/ugorji/go/codec ; \ 
go get -v github.com/cheggaaa/pb ; \ 
go get -v github.com/robfig/cron ; \ 
go get -v github.com/gorilla/schema ; \ 
go get -v github.com/martini-contrib/binding ; \ 
go get -v github.com/ant0ine/go-json-rest/rest ; \ 
go get -v github.com/olekukonko/tablewriter ; \ 
go get -v github.com/robertkrimen/otto ; \ 
go get -v github.com/stretchr/testify/mock ; \ 
go get -v github.com/bradfitz/gomemcache/memcache ; \ 
go get -v github.com/asaskevich/govalidator ; \ 
go get -v github.com/howeyc/gopass ; \ 
go get -v github.com/Shopify/sarama ; \ 
go get -v github.com/kr/pretty ; \ 
go get -v github.com/spf13/pflag ; \ 
go get -v github.com/disintegration/imaging ; \ 
go get -v github.com/gopherjs/gopherjs/js ; \ 
go get -v github.com/justinas/alice ; \ 
go get -v github.com/samuel/go-zookeeper/zk ; \ 
go get -v github.com/stretchr/testify/assert ; \ 
go get -v github.com/smartystreets/goconvey/convey ; \ 
go get -v github.com/onsi/gomega ; \ 
go get -v github.com/onsi/ginkgo ; \ 
go get -v github.com/stretchr/testify/require ; \ 
go get -v github.com/stretchr/testify/suite ; \ 
go get -v github.com/bmizerany/assert ; \ 
go get -v github.com/stretchr/testify/mock ; \ 
go get -v github.com/mattn/go-sqlite3 ; \ 
go get -v github.com/davecgh/go-spew/spew ; \ 
go get -v github.com/lib/pq ; \ 
go get -v github.com/go-sql-driver/mysql ; \ 
go get -v github.com/kr/pretty ; \ 
go get -v github.com/gorilla/mux ; \ 
go get -v github.com/onsi/gomega/gbytes ; \ 
go get -v github.com/onsi/gomega/gexec ; \ 
go get -v github.com/onsi/gomega/ghttp ; \ 
go get -v github.com/franela/goblin ; \ 
go get -v github.com/jarcoal/httpmock ; \ 
go get -v github.com/stretchrcom/testify/assert ; \ 
go get -v github.com/onsi/ginkgo/extensions/table ; \ 
go get -v github.com/ant0ine/go-json-rest/rest/test ; \ 
go get -v github.com/kylelemons/godebug/pretty ; \ 
go get -v github.com/golang/mock/gomock ; \ 
go get -v github.com/DATA-DOG/go-sqlmock ; \ 
go get -v github.com/onsi/ginkgo/reporters ; \ 
go get -v github.com/onsi/ginkgo/config ; \ 
go get -v github.com/facebookgo/ensure ; \ 
go get -v github.com/pivotal-golang/lager/lagertest ; \ 
go get -v github.com/PuerkitoBio/goquery ; \ 
go get -v github.com/cheekybits/is ; \ 
go get -v github.com/satori/go.uuid ; \ 
go get -v github.com/nu7hatch/gouuid ; \ 
go get -v github.com/hashicorp/consul/testutil ; \ 
go get -v github.com/google/gofuzz ; \ 
go get -v github.com/pborman/uuid ; \ 
go get -v github.com/erikstmartin/go-testdb ; \ 
go get -v github.com/rafaeljusto/redigomock ; \ 
go get -v github.com/garyburd/redigo/redis ; \ 
go get -v github.com/onsi/gomega/types ; \ 
go get -v github.com/cloudfoundry/cli/testhelpers/io ; \ 
go get -v github.com/golang/protobuf/proto ; \ 
go get -v github.com/remogatto/prettytest ; \ 
go get -v github.com/elazarl/goproxy ; \ 
go get -v github.com/BurntSushi/toml ; \ 
go get -v github.com/stretchr/gomniauth/test ; \ 
go get -v github.com/prometheus/client_model/go ; \ 
go get -v github.com/gogo/protobuf/proto ; \ 
go get -v github.com/onsi/gomega/format ; \ 
go get -v github.com/julienschmidt/httprouter ; \ 
go get -v github.com/r7kamura/gospel ; \ 
go get -v github.com/alicebob/miniredis ; \ 
go get -v github.com/go-martini/martini ; \ 
go get -v github.com/gorilla/websocket ; \ 
go get -v github.com/ziutek/mymysql/godrv ; \ 
go get -v github.com/nbio/st ; \ 
go get -v github.com/kr/pty ; \ 
go get -v github.com/orfjackal/gospec/src/gospec ; \ 
go get -v github.com/gogo/protobuf/jsonpb ; \ 
go get -v github.com/sclevine/agouti ; \ 
go get -v github.com/mitchellh/goamz/s3/s3test ; \ 
go get -v github.com/pivotal-golang/clock/fakeclock ; \ 
go get -v github.com/gavv/httpexpect ; \ 
go get -v github.com/hashicorp/terraform/helper/resource ; \ 
go get -v github.com/codegangsta/negroni ; \ 
go get -v github.com/dgrijalva/jwt-go ; \ 
go get -v github.com/google/cadvisor/info/v1/test ; \ 
go get -v github.com/motain/gocheck ; \ 
go get -v github.com/drewolson/testflight ; \ 
go get -v github.com/boltdb/bolt ; \ 
go get -v github.com/stretchr/testify/assert ; \ 
go get -v github.com/onsi/gomega ; \ 
go get -v github.com/gorilla/mux ; \ 
go get -v github.com/onsi/ginkgo ; \ 
go get -v github.com/golang/protobuf/proto ; \ 
go get -v github.com/smartystreets/goconvey/convey ; \ 
go get -v github.com/spf13/pflag ; \ 
go get -v github.com/codegangsta/cli ; \ 
go get -v github.com/go-sql-driver/mysql ; \ 
go get -v github.com/stretchr/testify/require ; \ 
go get -v github.com/prometheus/client_golang/prometheus ; \ 
go get -v github.com/hashicorp/terraform/terraform ; \ 
go get -v github.com/astaxie/beego ; \ 
go get -v github.com/gogo/protobuf/proto ; \ 
go get -v github.com/lib/pq ; \ 
go get -v github.com/spf13/cobra ; \ 
go get -v github.com/gin-gonic/gin ; \ 
go get -v github.com/mattn/go-sqlite3 ; \ 
go get -v github.com/BurntSushi/toml ; \ 
go get -v github.com/davecgh/go-spew/spew ; \ 
go get -v github.com/spf13/viper ; \ 
go get -v github.com/garyburd/redigo/redis ; \ 
go get -v github.com/hashicorp/terraform/plugin ; exit 0
RUN rm -rf $GOPATH/src/github.com/schollz && go get -v github.com/schollz/gobenchmarkservice
ENTRYPOINT gobenchmarkservice -client